[tool.poetry]
name = "pyraft"
version = "0.1.0"
description = "My Raft implementation"
authors = ["coffe <a.potapova8@g.nsu.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = "^0.30.6"
fastapi = "^0.115.4"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.31.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
raft = "pyraft.main:main"
node = "lock:node"
philosopher = "lock:philosopher"

[tool.poe.tasks]
sA = "poetry run raft -n ServerA -c config.json"
sB = "poetry run raft -n ServerB -c config.json"
sC = "poetry run raft -n ServerC -c config.json"